function dydt=WMVN_IP(t,y,N,M,G,A,g,L)
dydt=zeros(4*M+2*N,1);
for i=1:M
    dydt(i)=1/2 * sqrt( g / sqrt( y(2*M+i).^2 + y(3*M+i).^2) ) * y(2*M+i)./...
   sqrt( y(2*M+i).^2 + y(3*M+i).^2 ) + UmIP(G, y(4*M+1:4*M+N) , y(4*M+N+1:4*M+2*N),...
   y(i) , y(M+i),L );
    dydt(M+i)=1/2 * sqrt( g / sqrt(y(2*M+i).^2 + y(3*M+i).^2) ) * y(3*M+i)./...
   sqrt( y(2*M+i).^2 + y(3*M+i).^2 ) + VmIP(G , y(4*M+1:4*M+N), y(4*M+N+1:4*M+2*N),...
   y(i) , y(M+i),L);
   dydt(2*M+i) = -y(2*M+i) * dUmIPdx(G , y(4*M+1:4*M+N) ,y(4*M+N+1:4*M+2*N),...
   y(i) , y(M+i), L) - y(3*M+i) * dVmIPdx(G, y(4*M+1:4*M+N), y(4*M+N+1:4*M+2*N),...
   y(i) , y(M+i), L);
   dydt(3*M+i) = -y(2*M+i) * dUmIPdy(G, y(4*M+1:4*M+N), y(4*M+N+1:4*M+2*N),...
   y(i) , y(M+i), L) - y(3*M+i) * dVmIPdy(G, y(4*M+1:4*M+N), y(4*M+N+1:4*M+2*N),...
   y(i), y(M+i), L);
end
for i=1:N
   dydt(4*M+i)=UmIP(G , y(4*M+1:4*M+N) ,y(4*M+N+1:4*M+2*N),...
   y(4*M+i), y(4*M+N+i), L) - dPsiIPdy(A, y(1:M),...
   y(M+1:2*M), y(4*M+i), y(4*M+N+i), y(2*M+1:3*M), y(3*M+1:4*M), L);
   dydt(4*M+N+i)= VmIP(G, y(4*M+1:4*M+N), y(4*M+N+1:4*M+2*N),...
   y(4*M+i), y(4*M+N+i), L)+ dPsiIPdx(A, y(1:M),...
   y(M+1:2*M), y(4*M+i), y(4*M+N+i), y(2*M+1:3*M), y(3*M+1:4*M), L);
end
