function dydt=WMVN_IP(t,y,N,M,G,A,g,L)
dydt=zeros(4*M+2*N,1);
for i=1:M
    dydt(i)=1/2 * sqrt( g / sqrt( y(2*M+i).^2 + y(3*M+i).^2) ) * y(2*M+i)./...
   sqrt( y(2*M+i).^2 + y(3*M+i).^2 ) +...
   UmIP(G, mod(y(4*M+1:4*M+N),2*pi) , mod(y(4*M+N+1:4*M+2*N),2*pi),...
   mod(y(i),2*pi) , mod(y(M+i),2*pi), L );

    dydt(M+i)=1/2 * sqrt( g / sqrt(y(2*M+i).^2 + y(3*M+i).^2) ) ...
        * y(3*M+i)./...
   sqrt( y(2*M+i).^2 + y(3*M+i).^2 ) + ...
   VmIP(G , mod(y(4*M+1:4*M+N),2*pi), mod(y(4*M+N+1:4*M+2*N),2*pi),...
   mod(y(i),2*pi) , mod(y(M+i),2*pi), L);

   dydt(2*M+i) = -y(2*M+i) * dUmIPdx(G , mod(y(4*M+1:4*M+N),2*pi) ...
       ,mod(y(4*M+N+1:4*M+2*N), 2*pi),...
   mod(y(i), 2*pi) , mod(y(M+i), 2*pi), L) - y(3*M+i) * dVmIPdx(G,...
   mod(y(4*M+1:4*M+N), 2*pi), mod(y(4*M+N+1:4*M+2*N), 2*pi),...
   mod(y(i), 2*pi) , mod(y(M+i), 2*pi), L);

   dydt(3*M+i) = -y(2*M+i) * dUmIPdy(G, mod(y(4*M+1:4*M+N), 2*pi),...
       mod(y(4*M+N+1:4*M+2*N), 2*pi),...
   mod(y(i), 2*pi) , mod(y(M+i), 2*pi), L) - y(3*M+i) * dVmIPdy(G,...
   mod(y(4*M+1:4*M+N), 2*pi), mod(y(4*M+N+1:4*M+2*N), 2*pi),...
   mod(y(i), 2*pi), mod(y(M+i), 2*pi), L);
end
for i=1:N
   dydt(4*M+i)=UmIP(G , mod(y(4*M+1:4*M+N),2*pi) ,...
       mod(y(4*M+N+1:4*M+2*N),2*pi),...
   mod(y(4*M+i), 2*pi), mod(y(4*M+N+i), 2*pi), L) -...
   dPsiIPdy(A, mod(y(1:M),2*pi),...
  mod( y(M+1:2*M), 2*pi), mod(y(4*M+i), 2*pi), mod(y(4*M+N+i), 2*pi),...
   y(2*M+1:3*M), y(3*M+1:4*M), L);

   dydt(4*M+N+i)= VmIP(G, mod(y(4*M+1:4*M+N), 2*pi),...
       mod(y(4*M+N+1:4*M+2*N), 2*pi),...
   mod(y(4*M+i), 2*pi), mod(y(4*M+N+i), 2*pi), L)+...
   dPsiIPdx(A, mod(y(1:M), 2*pi),...
   mod(y(M+1:2*M), 2*pi), mod(y(4*M+i), 2*pi), mod(y(4*M+N+i), 2*pi),...
   y(2*M+1:3*M), y(3*M+1:4*M), L);

end
